### PR TITLE
machine/rp2040: fix PWM bug. Resolve #2592

### LINKED ISSUE #2592: PWM only produces max frequency of 1.8khz
No matter what value I give "period" in the code below, I can't get a higher PWM on the pin of 1.8Khz.

Save the following file as main.go....
[main.txt](https://github.com/tinygo-org/tinygo/files/7962672/main.txt)

### PR DESCRIPTION
**Pull request by soypat**
PTAL. Have not had a chance to test it but should regardless be more correct. Resolves https://github.com/tinygo-org/tinygo/issues/2592

### CODE REVIEW

File: src/machine/machine_rp2040_pwm.go [hunk 1]
```diff
@@ -280,6 +280,11 @@ func (pwm *pwmGroup) setPeriod(period uint64) error {
 	frac := rhs % 16
 	if whole > 0xff {
```
Comment (deadprogram) [inline src/machine/machine_rp2040_pwm.go]: Perhaps change all of this to:

```go
switch {
   case whole == 0:
      // do thing
   case whole > 0xff:
      // do other thing
}
```

Comment (soypat) [reply src/machine/machine_rp2040_pwm.go]: Great idea! I've force pushed changes.

File: src/machine/machine_rp2040_pwm.go [hunk 2]
```diff
@@ -278,8 +278,14 @@ func (pwm *pwmGroup) setPeriod(period uint64) error {
 	rhs := 16 * period / ((1 + phc) * periodPerCycle * (1 + topStart)) // right-hand-side of equation, scaled so frac is not divided
 	whole := rhs / 16
 	frac := rhs % 16
-	if whole > 0xff {
+	switch whole {
+	case 0xff:
```
Comment (kenbell) [inline src/machine/machine_rp2040_pwm.go]: This isn't equivalent?  This won't clamp 0x100 since it's not exactly 0xff?

Comment (soypat) [reply src/machine/machine_rp2040_pwm.go]: darn. I was about to break it even more. Sorry, I'm juggling university work and tinygo in a dangerous mix.

**Comment by deadprogram** [comment]
Thanks for the fix @soypat and for the review @kenbell now merging.
