### PR TITLE
machine/atsamd51: handle configuration of output-only SPI where input pin not connected

### LINKED ISSUE #1483: SPI1.Configure crashes for pygamer
I want to use TFT on pygamer, but calling machine.SPI1.Configure crash

```go
	machine.SPI1.Configure(machine.SPIConfig{
		SCK:       machine.SPI1_SCK_PIN,
		SDO:       machine.SPI1_SDO_PIN,
		SDI:       machine.SPI1_SDI_PIN,
	})
```

### PR DESCRIPTION
**Pull request by jypelle**

### CODE REVIEW

File: src/machine/machine_atsamd51.go [hunk 1]
```diff
@@ -1331,12 +1331,13 @@ func (spi SPI) Configure(config SPIConfig) error {
 
 	// Determine the input pinout (for SDI).
 	var dataInPinout uint32
-	SDIPinMode, SDIPad, ok := findPinPadMapping(spi.SERCOM, config.SDI)
+	var SDIPinMode PinMode
```
Comment (sago35) [inline src/machine/machine_atsamd51.go:1334]: I think it's a good change.

If we don't use SDI, is it OK for SDIPinMode and dataInPinout to be 0?
Do you know anything about it?

Comment (jypelle) [reply src/machine/machine_atsamd51.go:1334]: For SDIPinMode, it's only used when config.SDI != NoPin so it's ok.

For dataInPinout, I concede I'm not 100% sure. What i can say is that my adafruit pygamer tft screen works seemlessly with this change.

Comment (sago35) [reply src/machine/machine_atsamd51.go:1334]: The proposed amendment to #1408 ([conejoninja@6c39859](https://github.com/conejoninja/tinygo/commit/6c39859ec32b0d28ce3aadd0f0966079fc5cc380)) is almost the same code.
I think it's fine.

**Review by sago35 — DISMISSED** [review]
Looks good to me

**Comment by sago35** [comment]
findPinPadMapping is also called by other functions, such as the UART.
Therefore, it is better to include a crash prevention mechanism in findPinPadMapping().

**Comment by conejoninja** [comment]
I'd have set the variables dataInPinout & SDIPinMode, but as stated in my commit, I didn't know the implications of such change (setting them or not). I strongly recommend to do one way or another, until this is added, displays on the pygamer/pybadge/pyedge/... remain broken.

Linking the opened issue here : https://github.com/tinygo-org/tinygo/issues/1408

**Comment by deadprogram** [comment]
Thanks everyone who has worked on this. Now merging.

File: src/machine/machine_atsamd51.go (hunk 1 above)
Comment (aykevl) [reply src/machine/machine_atsamd51.go:1334]: Yes I think this is fine. With `dataInPinout` left zero, it will still read data from some arbitrary pin but as long as it is not read that should be fine (see `CTRLA.DIPO` field of the SPI peripheral, [here](http://ww1.microchip.com/downloads/en/DeviceDoc/60001507E.pdf#page=986)).
