### PR TITLE
cgo: fixes panic when FuncType.Results is nil

### LINKED ISSUE #3096: tinygo build panic appeared
hi, guys
     When I try to compile the wasm module with tinygo, the following panic message appears(environment：mac Mojave10.14.6,go version 1.17.8 darwin/amd64,tinygo,version 0.25.0):

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x428b234]

goroutine 1 [running]:
golang.org/x/tools/go/ast/astutil.Apply.func1()
	/Users/runner/go/pkg/mod/golang.org/x/tools@v0.1.11/go/ast/astutil/rewrite.go:48 +0x89
panic({0x82b8ec0, 0x9a303b0})
	/Users/runner/hostedtoolcache/go/1.18.1/x64/src/runtime/panic.go:838 +0x207
github.com/tinygo-org/tinygo/cgo.(*cgoPackage).isEquivalentAST(0x82a3000?, {0x8392290?, 0x0?}, {0x8392290?, 0x0})
	/Users/runner/work/tinygo/tinygo/cgo/cgo.go:944 +0x434
github.com/tinygo-org/tinygo/cgo.(*cgoPackage).isEquivalentAST(0x8?, {0x8392308?, 0xc004d90060?}, {0x8392308?, 0xc004b92b10})
	/Users/runner/work/tinygo/tinygo/cgo/cgo.go:991 +0x2db
github.com/tinygo-org/tinygo/cgo.(*cgoFile).getASTDeclNode(0xc000362a98, {0xc004a51790, 0x4}, {0x8, 0x0, {0x13903a80, 0x1, 0xc800f80}}, 0x7?)
	/Users/runner/work/tinygo/tinygo/cgo/cgo.go:1140 +0x9c5
github.com/tinygo-org/tinygo/cgo.(*cgoFile).getASTDeclName(0x0?, {0xc004a51790, 0x4}, {0x8, 0x0, {0x13903a80, 0x1, 0xc800f80}}, 0x1)
	/Users/runner/work/tinygo/tinygo/cgo/cgo.go:1119 +0xc5
github.com/tinygo-org/tinygo/cgo.(*cgoFile).walker(0x36?, 0x16?, 0xc0038dd430?)
	/Users/runner/work/tinygo/tinygo/cgo/cgo.go:1228 +0x157
github.com/tinygo-org/tinygo/cgo.Process.func3.1(0x4?)
	/Users/runner/work/tinygo/tinygo/cgo/cgo.go:315 +0x27
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc004b73020, {0x8392240?, 0xc004a6d610?}, {0x83101ff?, 0x0?}, 0x8?, {0x8392088?, 0xc004a867c0?})
	/Users/runner/go/pkg/mod/golang.org/x/tools@v0.1.11/go/ast/astutil/rewrite.go:199 +0x202
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc004b73020, {0x8392038?, 0xc004a88060?}, {0x83106f7?, 0x0?}, 0xc004a88060?, {0x8392240?, 0xc004a6d610?})
	/Users/runner/go/pkg/mod/golang.org/x/tools@v0.1.11/go/ast/astutil/rewrite.go:327 +0x39b
golang.org/x/tools/go/ast/astutil.(*application).applyList(0xc004b73020, {0x8392038?, 0xc004a88060}, {0x83106f7, 0x4})
	/Users/runner/go/pkg/mod/golang.org/x/tools@v0.1.11/go/ast/astutil/rewrite.go:484 +0xae
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc004b73020, {0x83923f8?, 0xc004a86800?}, {0x8310697?, 0x0?}, 0x8?, {0x8392038?, 0xc004a88060?})
	/Users/runner/go/pkg/mod/golang.org/x/tools@v0.1.11/go/ast/astutil/rewrite.go:353 +0x310
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc004b73020, {0x8392038?, 0xc004a88090?}, {0x83106f7?, 0x0?}, 0xc004a88090?, {0x83923f8?, 0xc004a86800?})
	/Users/runner/go/pkg/mod/golang.org/x/tools@v0.1.11/go/ast/astutil/rewrite.go:358 +0x4bf
golang.org/x/tools/go/ast/astutil.(*application).applyList(0xc004b73020, {0x8392038?, 0xc004a88090}, {0x83106f7, 0x4})
	/Users/runner/go/pkg/mod/golang.org/x/tools@v0.1.11/go/ast/astutil/rewrite.go:484 +0xae
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc004b73020, {0x83925b0?, 0xc004a70b90?}, {0x8310697?, 0x0?}, 0x8?, {0x8392038?, 0xc004a88090?})
	/Users/runner/go/pkg/mod/golang.org/x/tools@v0.1.11/go/ast/astutil/rewrite.go:353 +0x310
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc004b73020, {0x8392038?, 0xc004a880c0?}, {0x83106f7?, 0x0?}, 0xc004a880c0?, {0x83925b0?, 0xc004a70b90?})
	/Users/runner/go/pkg/mod/golang.org/x/tools@v0.1.11/go/ast/astutil/rewrite.go:392 +0xf7b
golang.org/x/tools/go/ast/astutil.(*application).applyList(0xc004b73020, {0x8392038?, 0xc004a880c0}, {0x83106f7, 0x4})
	/Users/runner/go/pkg/mod/golang.org/x/tools@v0.1.11/go/ast/astutil/rewrite.go:484 +0xae
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc004b73020, {0x8392308?, 0xc004a880f0?}, {0x8310697?, 0x0?}, 0x18?, {0x8392038?, 0xc004a880c0?})
	/Users/runner/go/pkg/mod/golang.org/x/tools@v0.1.11/go/ast/astutil/rewrite.go:353 +0x310
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc004b73020, {0x83922b8?, 0xc004a84500?}, {0x8310ad2?, 0x0?}, 0xc004a84500?, {0x8392308?, 0xc004a880f0?})
	/Users/runner/go/pkg/mod/golang.org/x/tools@v0.1.11/go/ast/astutil/rewrite.go:429 +0x1a29
golang.org/x/tools/go/ast/astutil.(*application).applyList(0xc004b73020, {0x83922b8?, 0xc004a84500}, {0x8310ad2, 0x5})
	/Users/runner/go/pkg/mod/golang.org/x/tools@v0.1.11/go/ast/astutil/rewrite.go:484 +0xae
golang.org/x/tools/go/ast/astutil.(*application).apply(0xc004b73020, {0x8392ab0?, 0xc004e48be0?}, {0x831070f?, 0x1435a648?}, 0x18?, {0x83922b8?, 0xc004a84500?})
	/Users/runner/go/pkg/mod/golang.org/x/tools@v0.1.11/go/ast/astutil/rewrite.go:435 +0xc8d
golang.org/x/tools/go/ast/astutil.Apply({0x83922b8?, 0xc004a84500}, 0xc004c6adb0, 0x0)
	/Users/runner/go/pkg/mod/golang.org/x/tools@v0.1.11/go/ast/astutil/rewrite.go:53 +0x166
github.com/tinygo-org/tinygo/cgo.Process.func3(0xc004d90420)
	/Users/runner/work/tinygo/tinygo/cgo/cgo.go:314 +0xbe
github.com/tinygo-org/tinygo/cgo.(*cgoFile).readNames(0xc000362a98, {0xc0001306e0, 0x146}, {0xc001cf1340?, 0x18, 0x2c}, {0xc0049c143d, 0xb}, 0xc0038de820)
	/Users/runner/work/tinygo/tinygo/cgo/libclang.go:187 +0x562
github.com/tinygo-org/tinygo/cgo.Process({0xc004a84900, 0xf, 0x10?}, {0xc000024104, 0x32}, 0xc0018662c0, {0xc004ae3400, 0x9, 0xc000024104?}, {0xc00012c270, ...})
	/Users/runner/work/tinygo/tinygo/cgo/cgo.go:307 +0xb85
github.com/tinygo-org/tinygo/loader.(*Package).parseFiles(0xc00177fa40)
	/Users/runner/work/tinygo/tinygo/loader/loader.go:448 +0x2bf
github.com/tinygo-org/tinygo/loader.(*Package).Parse(0xc00177fa40)
	/Users/runner/work/tinygo/tinygo/loader/loader.go:363 +0x7f
github.com/tinygo-org/tinygo/loader.(*Program).Parse(0xc002733790)
	/Users/runner/work/tinygo/tinygo/loader/loader.go:312 +0x65
github.com/tinygo-org/tinygo/builder.Build({0x7ffeefbffa07, 0x9}, {0x7ffeefbff9f0, 0x9}, 0xc00020e2d0, 0xc0038df7b0)
	/Users/runner/work/tinygo/tinygo/builder/build.go:202 +0x11e5
main.Build({0x7ffeefbffa07, 0x9}, {0x7ffeefbff9f0, 0x9}, 0xc0001782c0)
	/Users/runner/work/tinygo/tinygo/main.go:156 +0x18c
main.main()
	/Users/runner/work/tinygo/tinygo/main.go:1441 +0x3b95
```

someone can answer my question? Thanks for all.

### PR DESCRIPTION
**Pull request by codefromthecrypt**
FuncType.Results can be nil. This fixes the comparison and backfills relevant tests.

Fixes #3096

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
macOS failure looks like the same as #2892 ?

```
tinygo:ld.lld: error: undefined symbol: _notARealFunction
[19703](https://github.com/tinygo-org/tinygo/runs/8221221002?check_suite_focus=true#step:12:19704)
>>> referenced by /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tinygo492537698/main.o
[19704](https://github.com/tinygo-org/tinygo/runs/8221221002?check_suite_focus=true#step:12:19705)
failed to run tool: ld.lld
[19705](https://github.com/tinygo-org/tinygo/runs/8221221002?check_suite_focus=true#step:12:19706)
--- FAIL: TestFail (0.00s)
[19706](https://github.com/tinygo-org/tinygo/runs/8221221002?check_suite_focus=true#step:12:19707)
    fail
[19707](https://github.com/tinygo-org/tinygo/runs/8221221002?check_suite_focus=true#step:12:19708)
FAIL
```

File: cgo/cgo_test.go [hunk 1]
```diff
@@ -115,6 +115,85 @@ func TestCGo(t *testing.T) {
...
+		{
+			name:     "FuncDecl Type Results b nil",
+			a:        funcDeclA,
+			b:        funcDeclNoResults,
+			expected: false,
+		},
+	}
+
+	for _, tc := range testCases {
+		tc := tc // avoid a race condition
```
Comment (aykevl) [inline cgo/cgo_test.go]: Not a dealbreaker but because these tests aren't run in parallel it doesn't seem necessary. It doesn't really hurt either so :shrug: 

```suggestion
```

**Review by aykevl — COMMENTED** [review]
Can you add a test that actually tests for the issue in #3096? It looks like a particular kind of code triggers it, which is not covered in the cgo/testdata/*.go files.

**Comment by aykevl** [comment]
The `_notARealFunction` error message is noise. It just tests for a linker error, which results in some output on stderr. We should make this less confusing by redirecting stderr.

**Comment by deadprogram** [comment]
@codefromthecrypt did you see @aykevl comment on this PR?

https://github.com/tinygo-org/tinygo/pull/3136#pullrequestreview-1100940709

**Comment by codefromthecrypt** [comment]
@deadprogram thanks I missed it. yeap I can add a second layer test beyond the unit tests. np

**Comment by codefromthecrypt** [comment]
@FGadvancer I fixed the bug, but we should have an integration test that makes sure it stays fixed. Can you paste the code that led to this panic? It is better than me wildly guessing.

**Comment by codefromthecrypt** [comment]
It took a while for me to figure out from the stack trace what the bug was, but am over budget doing more than work provided. If someone is interested in raising a PR to obviate this adding the second layer of tests, works for me. If only one layer of tests isn't good enough and this bug is tolerable meanwhile, I also don't mind if someone closes this.

**Comment by deadprogram** [comment]
This seems better than it is right now, at the very least. Now squash/merging thank you for the code @codefromthecrypt
