### PR TITLE
src/os: make Environ() return a copy of the environment

### LINKED ISSUE #2646: os.Environ() returns live environment rather than copy
Tinygo's os tests include TestClearenv from upstream, but it fails frequently because it assumes os.Environ() returns a copy of the environment.
This is the case upstream, but in tinygo, it returns pointers to the live environment. Thus in tinygo, os.Environ() can go invalid the moment any environment variable is deleted.

We should probably disable TestClearenv until that's fixed, otherwise TestClearenv will continue to fail, causing spurious failures on unrelated changes in CI.

### PR DESCRIPTION
**Pull request by dgryski**
Fixes #2646

### CODE REVIEW

**Comment by dankegel** [comment]
this pull request should also bring back the test deleted by https://github.com/tinygo-org/tinygo/pull/2603

File: src/os/env.go [hunk 1]
```diff
@@ -137,5 +138,13 @@ func Clearenv() {
 // Environ returns a copy of strings representing the environment,
 // in the form "key=value".
 func Environ() []string {
-	return syscall.Environ()
+	orig := syscall.Environ()
+	single := strings.Join(orig, "")
```
Comment (dkegel-fastly) [inline src/os/env.go]: Upsteam does the copy in syscall.Environ(), we might want to do the same in case someone calls that directly?

**Comment by dgryski** [comment]
That probably makes sense.  I'll move this logic (or equivalent) there.

**Comment by dkegel-fastly** [comment]
Would it make sense to do a single allocation to copy libc_environ and then point to bits of it?  That might be faster...?

**Comment by dgryski** [comment]
Yeah, I was torn about doing that because we need to loop over the environment a few times instead of just once.  Let me try that approach and see what it looks like

**Comment by dgryski** [comment]
Now with a single allocation.

**Review by dkegel-fastly — COMMENTED** [review]
LGTM

File: src/syscall/syscall_libc.go [hunk 2]
```diff
@@ -235,20 +235,41 @@ func Mprotect(b []byte, prot int) (err error) {
...
 		rawEnvVar.length = length
-		envs = append(envs, envVar)
-		// This is the Go equivalent of "environ++" in C.
+		// pull off the number of bytes we need for this environment variable
+		var bs []byte
+		bs, b = b[:length], b[length:]
+		// copy over the bytes to the Go heap
+		copy(bs, envVar)
+		// convert trimmed slice to string
+		s := *(*string)(unsafe.Pointer(&bs))
```
Comment (aykevl) [inline src/syscall/syscall_libc.go:269]: This is a dirty trick... but I have to admit, this whole function isn't exactly clean and I wrote it originally.
(Dirty because it's not guaranteed that slice/string layout will stay the way it is now - although I don't see why it would need to change).

**Review by aykevl — APPROVED** [review]

**Comment by aykevl** [comment]
> Now with a single allocation.

Note that this can have the side effect of keeping more alive than needed. Imagine you only need a single value out of the environment. So you call `Environ()`, pick the one value, and keep that string around. Now all the environment strings can't be garbage collected.
Maybe that's fine, just noting in case that wasn't the intention.

**Comment by dgryski** [comment]
Good point about a single environment variable pinning the entire allocation. I think I'll add a comment to this function about that

**Comment by dkegel-fastly** [comment]
Yeah, that went through my head too, I should have mentioned it.
