### PR TITLE
Namespaced Wasm Imports so they don't conflict across modules, or reserved LLVM IR

### LINKED ISSUE #1559: Import uses the wrong module when function name is "write"
When setting the target as WASI specifying a module to import a function named `write`, the generated wasm code will import `"wasi_snapshot_preview1" "fd_write"` rather than a function called `write` from the correct module.

Example go program with the incorrect import:

```Go
package main

//go:wasm-module my_module
//export foo
func foo() int // <-- Works correctly

//go:wasm-module my_module
//export write
func bar() int // <-- imports fd_write from wasi_snapshot_preview1

func main() {
    foo()
    bar()
}
```

Compiled using `tinygo build -target=wasi -scheduler=none -wasm-abi=generic -o ./module.wasm main.go`

Result after converting main.wasm to wat:

```wat
(module
  (type (;0;) (func (result i32)))
  (type (;1;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;2;) (func (param i32 i32 i32) (result i32)))
  (type (;3;) (func))
  (type (;4;) (func (param i32 i32)))
  (import "my_module" "foo" (func $foo (type 0)))
  (import "wasi_snapshot_preview1" "fd_write" (func $__wasi_fd_write (type 1)))
  (func $memset (type 2) (param i32 i32 i32) (result i32)
    (local i32 i32 i32 i64)
    block  ;; label = @1
      local.get 2
      i32.eqz
      br_if 0 (;@1;)
      local.get 0
      local.get 1
      i32.store8
      local.get 2
      local.get 0
      i32.add
      local.tee 3
      i32.const -1
      i32.add
      local.get 1
      i32.store8
      local.get 2
      i32.const 3
      i32.lt_u
      br_if 0 (;@1;)
      local.get 0
      local.get 1
      i32.store8 offset=2
      local.get 0
      local.get 1
      i32.store8 offset=1
      local.get 3
      i32.const -3
      i32.add
      local.get 1
      i32.store8
      local.get 3
      i32.const -2
      i32.add
      local.get 1
      i32.store8
      local.get 2
      i32.const 7
      i32.lt_u
      br_if 0 (;@1;)
      local.get 0
      local.get 1
      i32.store8 offset=3
      local.get 3
      i32.const -4
      i32.add
      local.get 1
      i32.store8
      local.get 2
      i32.const 9
      i32.lt_u
      br_if 0 (;@1;)
      local.get 0
      i32.const 0
      local.get 0
      i32.sub
      i32.const 3
      i32.and
      local.tee 4
      i32.add
      local.tee 3
      local.get 1
      i32.const 255
      i32.and
      i32.const 16843009
      i32.mul
      local.tee 1
      i32.store
      local.get 3
      local.get 2
      local.get 4
      i32.sub
      i32.const -4
      i32.and
      local.tee 4
      i32.add
      local.tee 2
      i32.const -4
      i32.add
      local.get 1
      i32.store
      local.get 4
      i32.const 9
      i32.lt_u
      br_if 0 (;@1;)
      local.get 3
      local.get 1
      i32.store offset=8
      local.get 3
      local.get 1
      i32.store offset=4
      local.get 2
      i32.const -8
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -12
      i32.add
      local.get 1
      i32.store
      local.get 4
      i32.const 25
      i32.lt_u
      br_if 0 (;@1;)
      local.get 3
      local.get 1
      i32.store offset=24
      local.get 3
      local.get 1
      i32.store offset=20
      local.get 3
      local.get 1
      i32.store offset=16
      local.get 3
      local.get 1
      i32.store offset=12
      local.get 2
      i32.const -16
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -20
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -24
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -28
      i32.add
      local.get 1
      i32.store
      local.get 4
      local.get 3
      i32.const 4
      i32.and
      i32.const 24
      i32.or
      local.tee 5
      i32.sub
      local.tee 2
      i32.const 32
      i32.lt_u
      br_if 0 (;@1;)
      local.get 1
      i64.extend_i32_u
      local.tee 6
      i64.const 32
      i64.shl
      local.get 6
      i64.or
      local.set 6
      local.get 3
      local.get 5
      i32.add
      local.set 1
      loop  ;; label = @2
        local.get 1
        local.get 6
        i64.store
        local.get 1
        i32.const 24
        i32.add
        local.get 6
        i64.store
        local.get 1
        i32.const 16
        i32.add
        local.get 6
        i64.store
        local.get 1
        i32.const 8
        i32.add
        local.get 6
        i64.store
        local.get 1
        i32.const 32
        i32.add
        local.set 1
        local.get 2
        i32.const -32
        i32.add
        local.tee 2
        i32.const 31
        i32.gt_u
        br_if 0 (;@2;)
      end
    end
    local.get 0)
  (func $write (type 2) (param i32 i32 i32) (result i32)
    (local i32)
    global.get 0
    i32.const 16
    i32.sub
    local.tee 3
    global.set 0
    local.get 3
    local.get 2
    i32.store offset=12
    local.get 3
    local.get 1
    i32.store offset=8
    block  ;; label = @1
      block  ;; label = @2
        local.get 0
        local.get 3
        i32.const 8
        i32.add
        i32.const 1
        local.get 3
        i32.const 4
        i32.add
        call $__wasi_fd_write
        local.tee 0
        i32.eqz
        br_if 0 (;@2;)
        i32.const 0
        i32.const 8
        local.get 0
        local.get 0
        i32.const 76
        i32.eq
        select
        i32.store offset=65536
        i32.const -1
        local.set 0
        br 1 (;@1;)
      end
      local.get 3
      i32.load offset=4
      local.set 0
    end
    local.get 3
    i32.const 16
    i32.add
    global.set 0
    local.get 0)
  (func $_start (type 3)
    (local i32)
    i32.const 65540
    i32.const 0
    memory.size
    i32.const 16
    i32.shl
    i32.const 65540
    i32.sub
    i32.const 6
    i32.shr_u
    call $memset
    drop
    local.get 0
    local.get 0
    call $command-line-arguments.main)
  (func $command-line-arguments.main (type 4) (param i32 i32)
    call $foo
    drop
    call $write
    drop)
  (table (;0;) 1 1 funcref)
  (memory (;0;) 2)
  (global (;0;) (mut i32) (i32.const 65536))
  (export "memory" (memory 0))
  (export "_start" (func $_start))
  (export "command-line-arguments.main" (func $command-line-arguments.main)))
```

For comparison, the same file but changing the //go:export directive to anything
other than `write` outputs the correct import:

```Go
package main

//go:wasm-module my_module
//export foo
func foo() int // <-- Works correctly

//go:wasm-module my_module
//export bar
func bar() int // <-- Works correctly

func main() {
    foo()
    bar()
}
```

wat output:
```wat
(module
  (type (;0;) (func (result i32)))
  (type (;1;) (func (param i32 i32 i32) (result i32)))
  (type (;2;) (func))
  (type (;3;) (func (param i32 i32)))
  (import "my_module" "foo" (func $foo (type 0)))
  (import "my_module" "bar" (func $bar (type 0)))
  (func $memset (type 1) (param i32 i32 i32) (result i32)
    (local i32 i32 i32 i64)
    block  ;; label = @1
      local.get 2
      i32.eqz
      br_if 0 (;@1;)
      local.get 0
      local.get 1
      i32.store8
      local.get 2
      local.get 0
      i32.add
      local.tee 3
      i32.const -1
      i32.add
      local.get 1
      i32.store8
      local.get 2
      i32.const 3
      i32.lt_u
      br_if 0 (;@1;)
      local.get 0
      local.get 1
      i32.store8 offset=2
      local.get 0
      local.get 1
      i32.store8 offset=1
      local.get 3
      i32.const -3
      i32.add
      local.get 1
      i32.store8
      local.get 3
      i32.const -2
      i32.add
      local.get 1
      i32.store8
      local.get 2
      i32.const 7
      i32.lt_u
      br_if 0 (;@1;)
      local.get 0
      local.get 1
      i32.store8 offset=3
      local.get 3
      i32.const -4
      i32.add
      local.get 1
      i32.store8
      local.get 2
      i32.const 9
      i32.lt_u
      br_if 0 (;@1;)
      local.get 0
      i32.const 0
      local.get 0
      i32.sub
      i32.const 3
      i32.and
      local.tee 4
      i32.add
      local.tee 3
      local.get 1
      i32.const 255
      i32.and
      i32.const 16843009
      i32.mul
      local.tee 1
      i32.store
      local.get 3
      local.get 2
      local.get 4
      i32.sub
      i32.const -4
      i32.and
      local.tee 4
      i32.add
      local.tee 2
      i32.const -4
      i32.add
      local.get 1
      i32.store
      local.get 4
      i32.const 9
      i32.lt_u
      br_if 0 (;@1;)
      local.get 3
      local.get 1
      i32.store offset=8
      local.get 3
      local.get 1
      i32.store offset=4
      local.get 2
      i32.const -8
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -12
      i32.add
      local.get 1
      i32.store
      local.get 4
      i32.const 25
      i32.lt_u
      br_if 0 (;@1;)
      local.get 3
      local.get 1
      i32.store offset=24
      local.get 3
      local.get 1
      i32.store offset=20
      local.get 3
      local.get 1
      i32.store offset=16
      local.get 3
      local.get 1
      i32.store offset=12
      local.get 2
      i32.const -16
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -20
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -24
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -28
      i32.add
      local.get 1
      i32.store
      local.get 4
      local.get 3
      i32.const 4
      i32.and
      i32.const 24
      i32.or
      local.tee 5
      i32.sub
      local.tee 2
      i32.const 32
      i32.lt_u
      br_if 0 (;@1;)
      local.get 1
      i64.extend_i32_u
      local.tee 6
      i64.const 32
      i64.shl
      local.get 6
      i64.or
      local.set 6
      local.get 3
      local.get 5
      i32.add
      local.set 1
      loop  ;; label = @2
        local.get 1
        local.get 6
        i64.store
        local.get 1
        i32.const 24
        i32.add
        local.get 6
        i64.store
        local.get 1
        i32.const 16
        i32.add
        local.get 6
        i64.store
        local.get 1
        i32.const 8
        i32.add
        local.get 6
        i64.store
        local.get 1
        i32.const 32
        i32.add
        local.set 1
        local.get 2
        i32.const -32
        i32.add
        local.tee 2
        i32.const 31
        i32.gt_u
        br_if 0 (;@2;)
      end
    end
    local.get 0)
  (func $_start (type 2)
    (local i32)
    i32.const 65536
    i32.const 0
    memory.size
    i32.const 16
    i32.shl
    i32.const 65536
    i32.sub
    i32.const 6
    i32.shr_u
    call $memset
    drop
    local.get 0
    local.get 0
    call $command-line-arguments.main)
  (func $command-line-arguments.main (type 3) (param i32 i32)
    call $foo
    drop
    call $bar
    drop)
  (table (;0;) 1 1 funcref)
  (memory (;0;) 1)
  (global (;0;) (mut i32) (i32.const 65536))
  (export "memory" (memory 0))
  (export "_start" (func $_start))
  (export "command-line-arguments.main" (func $command-line-arguments.main)))
```

It also seems to import correctly when no module or export directive is set:
```Go
package main

//go:wasm-module my_module
//export foo
func foo() int // <-- Works correctly

func write() int // <-- imports from env

func main() {
    foo()
    write()
}
```

Gives:
```wat
(module
  (type (;0;) (func (result i32)))
  (type (;1;) (func (param i32 i32) (result i32)))
  (type (;2;) (func (param i32 i32 i32) (result i32)))
  (type (;3;) (func))
  (type (;4;) (func (param i32 i32)))
  (import "my_module" "foo" (func $foo (type 0)))
  (import "env" "command-line-arguments.write" (func $command-line-arguments.write (type 1)))
  (func $memset (type 2) (param i32 i32 i32) (result i32)
    (local i32 i32 i32 i64)
    block  ;; label = @1
      local.get 2
      i32.eqz
      br_if 0 (;@1;)
      local.get 0
      local.get 1
      i32.store8
      local.get 2
      local.get 0
      i32.add
      local.tee 3
      i32.const -1
      i32.add
      local.get 1
      i32.store8
      local.get 2
      i32.const 3
      i32.lt_u
      br_if 0 (;@1;)
      local.get 0
      local.get 1
      i32.store8 offset=2
      local.get 0
      local.get 1
      i32.store8 offset=1
      local.get 3
      i32.const -3
      i32.add
      local.get 1
      i32.store8
      local.get 3
      i32.const -2
      i32.add
      local.get 1
      i32.store8
      local.get 2
      i32.const 7
      i32.lt_u
      br_if 0 (;@1;)
      local.get 0
      local.get 1
      i32.store8 offset=3
      local.get 3
      i32.const -4
      i32.add
      local.get 1
      i32.store8
      local.get 2
      i32.const 9
      i32.lt_u
      br_if 0 (;@1;)
      local.get 0
      i32.const 0
      local.get 0
      i32.sub
      i32.const 3
      i32.and
      local.tee 4
      i32.add
      local.tee 3
      local.get 1
      i32.const 255
      i32.and
      i32.const 16843009
      i32.mul
      local.tee 1
      i32.store
      local.get 3
      local.get 2
      local.get 4
      i32.sub
      i32.const -4
      i32.and
      local.tee 4
      i32.add
      local.tee 2
      i32.const -4
      i32.add
      local.get 1
      i32.store
      local.get 4
      i32.const 9
      i32.lt_u
      br_if 0 (;@1;)
      local.get 3
      local.get 1
      i32.store offset=8
      local.get 3
      local.get 1
      i32.store offset=4
      local.get 2
      i32.const -8
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -12
      i32.add
      local.get 1
      i32.store
      local.get 4
      i32.const 25
      i32.lt_u
      br_if 0 (;@1;)
      local.get 3
      local.get 1
      i32.store offset=24
      local.get 3
      local.get 1
      i32.store offset=20
      local.get 3
      local.get 1
      i32.store offset=16
      local.get 3
      local.get 1
      i32.store offset=12
      local.get 2
      i32.const -16
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -20
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -24
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -28
      i32.add
      local.get 1
      i32.store
      local.get 4
      local.get 3
      i32.const 4
      i32.and
      i32.const 24
      i32.or
      local.tee 5
      i32.sub
      local.tee 2
      i32.const 32
      i32.lt_u
      br_if 0 (;@1;)
      local.get 1
      i64.extend_i32_u
      local.tee 6
      i64.const 32
      i64.shl
      local.get 6
      i64.or
      local.set 6
      local.get 3
      local.get 5
      i32.add
      local.set 1
      loop  ;; label = @2
        local.get 1
        local.get 6
        i64.store
        local.get 1
        i32.const 24
        i32.add
        local.get 6
        i64.store
        local.get 1
        i32.const 16
        i32.add
        local.get 6
        i64.store
        local.get 1
        i32.const 8
        i32.add
        local.get 6
        i64.store
        local.get 1
        i32.const 32
        i32.add
        local.set 1
        local.get 2
        i32.const -32
        i32.add
        local.tee 2
        i32.const 31
        i32.gt_u
        br_if 0 (;@2;)
      end
    end
    local.get 0)
  (func $_start (type 3)
    (local i32)
    i32.const 65536
    i32.const 0
    memory.size
    i32.const 16
    i32.shl
    i32.const 65536
    i32.sub
    i32.const 6
    i32.shr_u
    call $memset
    drop
    local.get 0
    local.get 0
    call $command-line-arguments.main)
  (func $command-line-arguments.main (type 4) (param i32 i32)
    (local i32)
    call $foo
    drop
    local.get 2
    local.get 2
    call $command-line-arguments.write
    drop)
  (table (;0;) 1 1 funcref)
  (memory (;0;) 1)
  (global (;0;) (mut i32) (i32.const 65536))
  (export "memory" (memory 0))
  (export "_start" (func $_start))
  (export "command-line-arguments.main" (func $command-line-arguments.main)))
```

### LINKED ISSUE #1643: Cannot import functions with the same name from different modules
Tinygo version:

`tinygo version 0.16.0 darwin/amd64 (using go version go1.15.8 and LLVM version 10.0.1)`

Example:

```go
package main

//go:wasm-module module1
//export foo
func module1_foo(int32) int32

//go:wasm-module module2
//export foo
func module2_foo(int32) int32

func main() {
        module1_foo(0)
        module2_foo(0)
}
```

Command line:

`tinygo build -target wasm -o main.wasm main.go`

Output in text format (via wasm2wat):

```wasm
(module
  (type (;0;) (func (param i32)))
  (type (;1;) (func (param i32 i32 i32 i32) (result i32)))
  (type (;2;) (func (param i32) (result i32)))
  (type (;3;) (func))
  (type (;4;) (func (param i32 i32 i32) (result i32)))
  (type (;5;) (func (param i32 i32)))
  (import "wasi_unstable" "fd_write" (func $fd_write (type 1)))
  (import "module2" "foo" (func $foo (type 2)))
  (func $__wasm_call_ctors (type 3))
  (func $memset (type 4) (param i32 i32 i32) (result i32)
    (local i32 i32 i32 i64)
    block  ;; label = @1
      local.get 2
      i32.eqz
      br_if 0 (;@1;)
      local.get 0
      local.get 1
      i32.store8
      local.get 2
      local.get 0
      i32.add
      local.tee 3
      i32.const -1
      i32.add
      local.get 1
      i32.store8
      local.get 2
      i32.const 3
      i32.lt_u
      br_if 0 (;@1;)
      local.get 0
      local.get 1
      i32.store8 offset=2
      local.get 0
      local.get 1
      i32.store8 offset=1
      local.get 3
      i32.const -3
      i32.add
      local.get 1
      i32.store8
      local.get 3
      i32.const -2
      i32.add
      local.get 1
      i32.store8
      local.get 2
      i32.const 7
      i32.lt_u
      br_if 0 (;@1;)
      local.get 0
      local.get 1
      i32.store8 offset=3
      local.get 3
      i32.const -4
      i32.add
      local.get 1
      i32.store8
      local.get 2
      i32.const 9
      i32.lt_u
      br_if 0 (;@1;)
      local.get 0
      i32.const 0
      local.get 0
      i32.sub
      i32.const 3
      i32.and
      local.tee 4
      i32.add
      local.tee 3
      local.get 1
      i32.const 255
      i32.and
      i32.const 16843009
      i32.mul
      local.tee 1
      i32.store
      local.get 3
      local.get 2
      local.get 4
      i32.sub
      i32.const -4
      i32.and
      local.tee 4
      i32.add
      local.tee 2
      i32.const -4
      i32.add
      local.get 1
      i32.store
      local.get 4
      i32.const 9
      i32.lt_u
      br_if 0 (;@1;)
      local.get 3
      local.get 1
      i32.store offset=8
      local.get 3
      local.get 1
      i32.store offset=4
      local.get 2
      i32.const -8
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -12
      i32.add
      local.get 1
      i32.store
      local.get 4
      i32.const 25
      i32.lt_u
      br_if 0 (;@1;)
      local.get 3
      local.get 1
      i32.store offset=24
      local.get 3
      local.get 1
      i32.store offset=20
      local.get 3
      local.get 1
      i32.store offset=16
      local.get 3
      local.get 1
      i32.store offset=12
      local.get 2
      i32.const -16
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -20
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -24
      i32.add
      local.get 1
      i32.store
      local.get 2
      i32.const -28
      i32.add
      local.get 1
      i32.store
      local.get 4
      local.get 3
      i32.const 4
      i32.and
      i32.const 24
      i32.or
      local.tee 5
      i32.sub
      local.tee 2
      i32.const 32
      i32.lt_u
      br_if 0 (;@1;)
      local.get 1
      i64.extend_i32_u
      local.tee 6
      i64.const 32
      i64.shl
      local.get 6
      i64.or
      local.set 6
      local.get 3
      local.get 5
      i32.add
      local.set 1
      loop  ;; label = @2
        local.get 1
        local.get 6
        i64.store
        local.get 1
        i32.const 24
        i32.add
        local.get 6
        i64.store
        local.get 1
        i32.const 16
        i32.add
        local.get 6
        i64.store
        local.get 1
        i32.const 8
        i32.add
        local.get 6
        i64.store
        local.get 1
        i32.const 32
        i32.add
        local.set 1
        local.get 2
        i32.const -32
        i32.add
        local.tee 2
        i32.const 31
        i32.gt_u
        br_if 0 (;@2;)
      end
    end
    local.get 0)
  (func $_start (type 3)
    (local i32)
    i32.const 65780
    i32.const 0
    memory.size
    i32.const 16
    i32.shl
    i32.const 65780
    i32.sub
    i32.const 6
    i32.shr_u
    call $memset
    drop
    local.get 0
    local.get 0
    call $command-line-arguments.main
    i32.const 0
    i32.const 1
    i32.store8 offset=65772
    call $runtime.scheduler)
  (func $command-line-arguments.main (type 5) (param i32 i32)
    i32.const 0
    call $foo
    drop
    i32.const 0
    call $foo
    drop)
  (func $runtime.scheduler (type 3)
    (local i32)
    block  ;; label = @1
      loop  ;; label = @2
        i32.const 0
        i32.load8_u offset=65772
        br_if 1 (;@1;)
        i32.const 0
        i32.load offset=65776
        local.tee 0
        i32.eqz
        br_if 1 (;@1;)
        i32.const 0
        local.get 0
        i32.load
        i32.store offset=65776
        local.get 0
        i32.const 0
        i32.store
        local.get 0
        i32.load offset=12
        local.tee 0
        local.get 0
        i32.load
        call_indirect (type 0)
        br 0 (;@2;)
      end
    end)
  (func $go_scheduler (type 3)
    call $runtime.scheduler)
  (func $runtime.lookupPanic (type 3)
    i32.const 65536
    i32.const 18
    call $runtime.runtimePanic)
  (func $runtime.runtimePanic (type 5) (param i32 i32)
    i32.const 65600
    i32.const 22
    call $runtime.printstring
    local.get 0
    local.get 1
    call $runtime.printstring
    call $runtime.printnl
    unreachable
    unreachable)
  (func $runtime.nilPanic (type 3)
    i32.const 65568
    i32.const 23
    call $runtime.runtimePanic)
  (func $runtime.printnl (type 3)
    i32.const 13
    call $runtime.putchar
    i32.const 10
    call $runtime.putchar)
  (func $runtime.putchar (type 0) (param i32)
    (local i32 i32)
    block  ;; label = @1
      i32.const 0
      i32.load offset=65632
      local.tee 1
      i32.const 119
      i32.le_u
      br_if 0 (;@1;)
      call $runtime.lookupPanic
      unreachable
    end
    i32.const 0
    local.get 1
    i32.const 1
    i32.add
    local.tee 2
    i32.store offset=65632
    local.get 1
    i32.const 65648
    i32.add
    local.get 0
    i32.store8
    block  ;; label = @1
      block  ;; label = @2
        local.get 0
        i32.const 255
        i32.and
        i32.const 10
        i32.eq
        br_if 0 (;@2;)
        local.get 1
        i32.const 119
        i32.ne
        br_if 1 (;@1;)
      end
      i32.const 0
      local.get 2
      i32.store offset=65628
      i32.const 1
      i32.const 65624
      i32.const 1
      i32.const 65768
      call $fd_write
      drop
      i32.const 0
      i32.const 0
      i32.store offset=65632
    end)
  (func $runtime.printstring (type 5) (param i32 i32)
    (local i32)
    i32.const 0
    local.set 2
    block  ;; label = @1
      loop  ;; label = @2
        local.get 2
        local.get 1
        i32.ge_s
        br_if 1 (;@1;)
        local.get 0
        local.get 2
        i32.add
        i32.load8_u
        call $runtime.putchar
        local.get 2
        i32.const 1
        i32.add
        local.set 2
        br 0 (;@2;)
      end
    end)
  (func $resume (type 3)
    call $runtime.resume$1
    unreachable)
  (func $runtime.resume$1 (type 3)
    call $runtime.nilPanic
    unreachable)
  (table (;0;) 1 1 funcref)
  (memory (;0;) 16)
  (global (;0;) (mut i32) (i32.const 65536))
  (global (;1;) i32 (i32.const 65780))
  (global (;2;) i32 (i32.const 65536))
  (global (;3;) i32 (i32.const 65780))
  (global (;4;) i32 (i32.const 65536))
  (global (;5;) i32 (i32.const 0))
  (global (;6;) i32 (i32.const 1))
  (export "memory" (memory 0))
  (export "__wasm_call_ctors" (func $__wasm_call_ctors))
  (export "memset" (func $memset))
  (export "_start" (func $_start))
  (export "__heap_base" (global 1))
  (export "command-line-arguments.main" (func $command-line-arguments.main))
  (export "go_scheduler" (func $go_scheduler))
  (export "resume" (func $resume))
  (export "__dso_handle" (global 2))
  (export "__data_end" (global 3))
  (export "__global_base" (global 4))
  (export "__memory_base" (global 5))
  (export "__table_base" (global 6))
  (data (;0;) (i32.const 65536) "index out of range\00\00\00\00\00\00\00\00\00\00\00\00\00\00nil pointer dereference\00\00\00\00\00\00\00\00\00panic: runtime error: ")
  (data (;1;) (i32.const 65624) "p\00\01\00\00\00\00\00"))
```

### PR DESCRIPTION
**Pull request by torch2424**
closes #1643
closes #1559

Kind of relates to #1647
Doesn't fix, but puts on the right path I think, for relates to #1648

So this PR was opened from a discussion in the tinygo slack: https://gophers.slack.com/archives/CDJD3SUP6/p1614201204223100 . Involving a conflict with wasm imports with the name of `write`. Which conflicts with the LLVM IR `@write`, and requires decoupling the LLVM IR symbol, and the `wasm-import-name`.

I tested this pr with the following code: https://github.com/torch2424/tinygo-compiler-playground (Which also contains the output LLVM IR of this current PR) , and ran the tests: `go test -target=wasm` and `make wasmtest`. 

### Screenshots of tests and things

Screenshot from 2021-02-24 18-20-02
Screenshot from 2021-02-24 18-15-57
Screenshot from 2021-02-24 18-14-04

### CODE REVIEW

**Comment by torch2424** [comment]
Oops, looks like my fork got a little weird, Let me force push to this branch based on my current branch :smile: 

EDIT: Ah! The actual issue was that I tried to merge into `release`, and not `dev` :upside_down_face: Fixing that now!

EDIT2: This is now for real good to go! :smile: :tada:

**Comment by deadprogram** [comment]
Hello @torch2424 thanks for this contribution.

Looks like there are some problems with the CI build: https://app.circleci.com/pipelines/github/tinygo-org/tinygo/4409/workflows/09f56573-cf9f-4d30-af51-fc15dfc75753/jobs/24355/parallel-runs/0/steps/0-121?invite=true

It appears that you need to run `go fmt` on the test output.

Separately, please make sure you rebase off of the most current `dev` branch to pickup some CI fixes from yesterday/

Thank you!

**Comment by torch2424** [comment]
Hello @deadprogram Thanks for the tips! :smile: 

> Looks like there are some problems with the CI build: https://app.circleci.com/pipelines/github/tinygo-org/tinygo/4409/workflows/09f56573-cf9f-4d30-af51-fc15dfc75753/jobs/24355/parallel-runs/0/steps/0-121?invite=true

> It appears that you need to run go fmt on the test output.

So I tried running `go fmt` and `gofmt -w` but it just gives the same error unfortunately :( 

Screenshot from 2021-02-25 11-13-29

Though, I am a bit confused why this would be happening? As I don't know why the test output is incorrectly formatted for the fix that I made? :thinking: 

> Separately, please make sure you rebase off of the most current dev branch to pickup some CI fixes from yesterday/

I made sure to do that! Looking at my branch, I am now rebased on top of: https://github.com/torch2424/tinygo/commit/e76729c6f39772542f0e4f4f85f5a41f655fa505 . Which seems to match up with what is at the HEAD of `tinygo:dev` :smile: :tada:

**Comment by torch2424** [comment]
> So I tried running `go fmt` and `gofmt -w` but it just gives the same error unfortunately :( 

So I did some digging around the makefile, and I just had to run the fmt in the makefile, `make fmt`.  :smile: 

---

Things are starting to pass in the CI, so I think this is good to go @deadprogram ! :smile: :tada:

File: compiler/symbol.go [hunk 1]
```diff
@@ -151,8 +153,13 @@ func (c *compilerContext) getFunction(fn *ssa.Function) llvm.Value {
 	if info.exported {
 		// Set the wasm-import-module attribute if the function's module is set.
 		if info.module != "" {
+
+			// We need to add the wasm-import-module and the wasm-import-name
 			wasmImportModuleAttr := c.ctx.CreateStringAttribute("wasm-import-module", info.module)
 			llvmFn.AddFunctionAttr(wasmImportModuleAttr)
+
+			wasmImportNameAttr := c.ctx.CreateStringAttribute("wasm-import-name", info.importName)
+			llvmFn.AddFunctionAttr(wasmImportNameAttr)
```
Comment (aykevl) [inline compiler/symbol.go]: Perhaps this needs an extra check that `info.importName` is not unset (an empty string)?

File: compiler/symbol.go [hunk 2]
```diff
@@ -207,7 +214,16 @@ func (info *functionInfo) parsePragmas(f *ssa.Function) {
...
 				}
-				info.linkName = parts[1]
+
+				// Set the wasmimport name and the llvm link name
+				info.importName = parts[1]
+
+				if info.module == "" {
+					info.linkName = info.importName
+				} else {
+					info.linkName = fmt.Sprintf("tinygo_wasm_import_%s_%s", info.module, info.importName)
```
Comment (aykevl) [inline compiler/symbol.go]: You are here introducing an order dependency between `//go:wasm-module` and `//export`: using `//export` before `//go:wasm-module` would change the behavior which is probably not expected.
Also, you're setting `info.importName` for all systems, not just WebAssembly? I guess LLVM will ignore it but it doesn't seem clean to me.

Instead of this if/else, I would move this if/else right after the for loop (putting `parts[1]` in a temporary variable). Something like this:

```go
if info.module != "" {
    // WebAssembly import
    info.importName = importName
} else {
    info.linkName = importName
}
```

Note, in particular, that this _doesn't_ change the link name. I think that's fine (and perhaps better): a TinyGo function name is unlikely to conflict with a name from another programming language with names such as `main.someExportedName` or `github.com/user/pkg/subpkg.someFunction`.

**Comment by torch2424** [comment]
Thanks for the review @aykevl ! :smile: 

So I addressed the first comment! 

and then for the second suggestion I tried moving it after the for loop, but then I get runtime panics (I added a screenshot), and I couldn't figure out why that was happening. :thinking: But! I was going to start heading out for the day, so I just pushed up where I'm at. But no worries, I'm sure I'll figure out what is going on. :smile: 

Screenshot from 2021-02-25 19-15-18

Once everything is good to go I'll add a mention :smile: :+1:

**Comment by torch2424** [comment]
@deadprogram @aykevl Alright! So I fixed the bug I had yesterday! :smile: :tada: 

I saw the CI was passing, but then found an uneeded comment, removed it, and then re-ran `make fmt`. And my example is still working! :tada: 

Screenshot from 2021-02-26 13-04-07


So I think this is good to go! :smile:

**Comment by deadprogram** [comment]
This is some great work @torch2424 thank you for all of the updates to feedback.

Would you prefer that I squash the commits before merging, or would you like to do that yourself?

File: compiler/symbol.go [hunk 3]
```diff
@@ -191,6 +200,10 @@ func (info *functionInfo) parsePragmas(f *ssa.Function) {
 		return
 	}
 	if decl, ok := f.Syntax().(*ast.FuncDecl); ok && decl.Doc != nil {
+
+		// Our importName for a wasm module (if we are compiling to wasm), or llvm link name
+		var importName string = ""
```
Comment (aykevl) [inline compiler/symbol.go]: Just a nitpick: this can be declared slightly shorter as follows:

```go
importName := ""
```

or like this:

```go
var importName string
```

**Review by aykevl — APPROVED** [review]
Looks good to me!

**Comment by torch2424** [comment]
Ah! My apologies, been handling some family stuff as of lately! :smile: 

@deadprogram 

> Would you prefer that I squash the commits before merging, or would you like to do that yourself?

First, thank you for the kind words! :smile: :tada: Please feel free to squash this, I'd very much appreciate it :smile: 

---

@aykevl

Thank you for the review. Made the suggested change, this should be good to go! :smile: :tada:

**Comment by deadprogram** [comment]
Thank you so very much for all the effort on this contribution. Now squash/merging.

**Comment by torch2424** [comment]
@deadprogram @aykevl Yay! Thank you very much for the review, and squashing / merging! :smile: :tada:
