### PR TITLE
Fix miscompile of static calls to closures

### LINKED ISSUE #508: Closures and channel operations result in a bug
The following doesn't produce the expected output:

```go
package main

var strch = make(chan string)

func main() {
	strch := strch // comment this line to avoid the bug
	go func() {
		println("sending...")
		strch <- "hello"
		println("sent!")
	}()
	println(<-strch)
}
```

There appears to be some sort of interaction between closures and channel operations that goes wrong.

### PR DESCRIPTION
**Pull request by jadr2ddude**
This PR fixes #508

Previously, spawning a goroutine with a closure whose function is statically known would result in a call that did not pass in the closure context. This resulted in undefined behavior. After copying in the appropriate context extraction code, the function-lowering pass attempted to transform the `makeGoroutine` operation, which caused the code to compile but have an LLVM assertion failure. The relevant code in the function-lowering pass has been modified to ignore `makeGoroutine` calls.

### CODE REVIEW

**Comment by jadr2ddude** [comment]
I added a test and it appears that there is another lowering bug for the `tasks` scheduler.

**Comment by jadr2ddude** [comment]
Alright, that bug should have been fixed.

File: compiler/func-lowering.go [hunk 1]
```diff
@@ -182,7 +186,9 @@ func (c *Compiler) LowerFuncValues() {
 								panic("expected a inttoptr")
 							}
 							for _, use := range getUses(inttoptr) {
-								c.addFuncLoweringSwitch(funcID, use, c.emitStartGoroutine, functions)
+								c.addFuncLoweringSwitch(funcID, use, func(funcPtr llvm.Value, params []llvm.Value) llvm.Value {
+									return c.emitStartGoroutine(funcPtr, params[:len(params)-1])
```
Comment (aykevl) [inline compiler/func-lowering.go]: Can you add a comment explaining why this last parameter must be stripped?

File: compiler/compiler.go [hunk 2]
```diff
@@ -1100,7 +1106,7 @@ func (c *Compiler) parseInstr(frame *Frame, instr ssa.Instruction) {
 			params = append(params, context) // context parameter
 			switch c.selectScheduler() {
 			case "coroutines":
-				params = append(params, llvm.ConstPointerNull(c.i8ptrType)) // parent coroutine handle
+				// nothing special here
```
Comment (aykevl) [inline compiler/compiler.go]: "nothing special here" is not very informative. Can you add a comment instead that explains why nothing should be added as a parameter?
