### PR TITLE
fixes `./...` syntax in `tinygo test`

### LINKED ISSUE #2892: Running tinygo test ./... fails
Running `tinygo test ./...` does not properly resolve all the packages recursively.

### PR DESCRIPTION
**Pull request by jcchavezs**
Adds proper support for `./...` syntax which was broken or maybe never intended to be supported and it only somehow worked because we use `go list` underneath. Allowing to use `./...` is actually a good experience in `go test`.

For example, running the tinygo@0.23.0 like:

```
$ tinygo test ./tests/testing/threedots/...
ok      github.com/tinygo-org/tinygo/tests/testing/threedots/pass       0.106s
```

whereas `./tests/testing/threedots` has two packages.

Closes #2892

### CODE REVIEW

**Comment by dkegel-fastly** [comment]
Could you link to (and if needed, file) a tinygo issue describing the problem you're trying to solve?  Thanks!

**Comment by dkegel-fastly** [comment]
Could you link to (and if needed, file) a tinygo issue describing the problem you're trying to solve?  Thanks!

File: loader/loader.go [hunk 1]
```diff
@@ -89,7 +90,7 @@ type Package struct {
 // Load loads the given package with all dependencies (including the runtime
 // package). Call .Parse() afterwards to parse all Go files (including CGo
 // processing, if necessary).
-func Load(config *compileopts.Config, inputPkgs []string, clangHeaders string, typeChecker types.Config) (*Program, error) {
+func Load(config *compileopts.Config, inputPkg string, clangHeaders string, typeChecker types.Config) (*Program, error) {
```
Comment (jcchavezs) [inline loader/loader.go:107]: I turned this into a single package for a few reasons:
1. It is used for single package only everywhere.
2. It is easier to deal with a single package.
3. [This error](https://github.com/tinygo-org/tinygo/pull/2885/files#diff-8e9af1e483632eac17610237caaa5f879ea7bfb3e1e1ea228e45a17c770b9432L231) is only looking at one package and it is actually thought of a single package

**Comment by jcchavezs** [comment]
@dkegel-fastly I linked the problem in the description. Do you want me to create a github issue?

**Comment by dkegel-fastly** [comment]
Yeah, at least for now, it would help if you had a github issue / github PR pair for each individual problem you are solving.  (I used to try to do multiple problems in one PR, but life is better with just one problem per PR, linked to a clear issue with reproducer.)

**Comment by jcchavezs** [comment]
Did a cherry-pick of [this commit](https://github.com/tinygo-org/tinygo/pull/2894/commits/8bdb2a1d6d70871172f2dcb889a11bd62d0cda42) to try the smoke test cc @dkegel-fastly

**Comment by jcchavezs** [comment]
It is green :D @dkegel-fastly

**Comment by dkegel-fastly** [comment]
I would suggest cleaning up the commit history in this branch a bit... make it looks like you got it right the first try.  No need to show dirty laundry!

**Comment by jcchavezs** [comment]
I can do that but I wonder if we keep this as it is because there are some
learnings in the mistakes and do the clean up of messaging by squashing the
merge?

**Comment by deadprogram** [comment]
Hello, @jcchavezs and @dkegel-fastly 

Having atomic commits and a clean history is part of our merge/rebase criteria. If you want to preserve additional info, I would suggest keep that in a branch on a fork.

Hopefully that helps clarify. Thank you!

**Comment by jcchavezs** [comment]
Thanks for the clarification. I will do so.

**Comment by jcchavezs** [comment]
I cleaned up the commits.

**Comment by jcchavezs** [comment]
Can we get this merged please?

**Comment by dkegel-fastly** [comment]
Give it a couple days :-)

**Comment by jcchavezs** [comment]
Shall we?

**Comment by dgryski** [comment]
I'll review this today.

**Review by dgryski — APPROVED** [review]
LGTM

**Comment by deadprogram** [comment]
Thank you very much for working on this @jcchavezs now merging.
