### PR TITLE
Ensure build output directory is created

### LINKED ISSUE #4687: `tinygo build -o /path/to/out` does not create intermediate directories, like `go build` does
- `go build -o /path/to/out .` creates `/path/to/` if needed, before starting the build.
- `tinygo build -o /path/to/out .` **does not** create `/path/to/` if the directory doesn't exist, failing the build with the slightly confusing message "open /path/to/out: no such file or directory"

This is confusing behaviour, but also makes the use of build tooling, like [GoReleaser](https://goreleaser.com/), challenging as substituting `tinygo` in for `go` in the build configuration doesn't work as expected, and throws the error: "open [your output path]: no such file or directory".

<details>
<summary>Repoducing the issue</summary>

Get into a Go project directory that can compile with Go and TinyGo.

```sh
# Create a space for the experiment & show the structure
$ mkdir -p /tmp/experiment

$ tree /tmp/experiment
/tmp/experiment

# Build to a directory that does not exist with tinygo: failure
$ tinygo build -o /tmp/experiment/somedir/tinygo-built .
open /tmp/experiment/somedir/tinygo-built: no such file or directory

$ tree /tmp/experiment
/tmp/experiment


# Create the directory manually, then try again: success
$ mkdir /tmp/experiment/somedir
$ tinygo build -o /tmp/experiment/somedir/tinygo-built .

$ tree /tmp/experiment
/tmp/experiment
└── somedir
    └── tinygo-built


# Remove that directory, then build with go instead: success
$ rm -rf /tmp/experiment/somedir
$ tree /tmp/experiment
/tmp/experiment

$ go build -o /tmp/experiment/somedir/go-built .

$ tree /tmp/experiment
/tmp/experiment
└── somedir
    └── go-built

```

</details>

### PR DESCRIPTION
**Pull request by jphastings**
`tinygo build -o /path/to/out .` expected `/path/to` to already exist, which is different behaviour to `go build`. This change ensures tinygo creates any directories needed to be able to build to the specified output dir.

I wasn't certain how to effectively test this change within this repo (this is my first TinyGo contribution), any advice would be welcome!

fixes #4687

### CODE REVIEW

File: builder/build.go [hunk 1]
```diff
@@ -604,6 +604,11 @@ func Build(pkgName, outpath, tmpdir string, config *compileopts.Config) (BuildRe
 		},
 	}
 
+	// Create the output directory, if needed
+	if err := os.MkdirAll(filepath.Dir(outpath), 0777); err != nil {
```
Comment (jphastings) [inline builder/build.go:608]: I picked `777` to match the files' `666` permissions later in this code.

**Review by leongross — APPROVED** [review]
Lgtm. Imo there is no need to add tests for this, since we don't want to test standard library functionality

**Comment by deadprogram** [comment]
Thanks for adding this @jphastings and to @leongross for review. Now merging.
