### PR TITLE
interp: add tests and implement runtime.sliceCopy

### LINKED ISSUE #437: error: interp: branch on a non-const-propagated constant expression
This error happened when compiling https://github.com/diamondburned/smart-contract-go/blob/master/examples/transfer-back/main.go with `/tinygo build -o ./main.wasm`.

With `-printir`: http://0x0.st/zLo5.txt

`error: interp: branch on a non-constant` is returned with `-gc none`.

Since Google suggests something about `const`s not being supported, I wrote some smaller code to confirm that, but couldn't.

### PR DESCRIPTION
**Pull request by aykevl**
Two changes that depend on each other. I can split out the PR if that makes it easier to review.

* Add tests. Start out with a basic test to see whether interp roughly works.
* implement `runtime.sliceCopy` in the interp package. That function uses lots of pointer casting so it's hard to interpret it directly, therefore I implemented it directly in interp.

This change gets 3 packages to compile: encoding/base32, encoding/base64, and encoding/pem. With that, compiling encoding/json is one step closer.

Fixes #437.

### CODE REVIEW

**Comment by aykevl** [comment]
Rebased to fix merge conflicts.

File: interp/values.go [hunk 1]
```diff
@@ -98,13 +98,33 @@ func (v *LocalValue) GetElementPtr(indices []uint32) Value {
...
+	}
+	panic("interp: unknown GEP")
+}
+
+// stripPointerCasts removes all bitcasts from a pointer value, if there are
+// any.
+func (v *LocalValue) stripPointerCasts() *LocalValue {
+	value := v.Underlying
+	for {
+		if !value.IsAConstantExpr().IsNil() {
```
Comment (jadr2ddude) [inline interp/values.go]: The comment on this function implies that this will strip all bitcasts from the value. However, this function does nothing if the input is not a constant. Either this should be changed to remove all bitcasts, or the comment should indicate that this does not work on non-constant bitcasts.

Comment (aykevl) [reply interp/values.go]: Fixed it.
